version: '3'

services:
  mysql:
    image: 'mysql'
    container_name: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=example
     - MYSQL_DATABASE=docker_mysql
    ports:
      - "3307:3306"
    volumes:
      - ./bewise/mydb:/var/lib/mysql

  flask:
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: flask
    command: python3 app.py
    volumes:
      - .:/usr/src/apps/app
    ports:
    - "8000:5000"
    depends_on:
      - mysql
